Xresources:
  font: IBM Plex Mono
  size: 15
  cwscale: 1
  chscale: 1
  bgcolor: '#1E1E1E'
  color0: '#171717'
  color1: '#FF5E5E'
  color2: '#9CE82B'
  color3: '#F0E68C'
  color4: '#008AFF'
  color5: '#E88CFF'
  color6: '#87CEFA'
  color7: '#DCDCCC'
  color8: '#737373'
  color9: '#FF7878'
  color10: '#9ACD32'
  color11: '#EEE8AA'
  color12: '#4F98FF'
  color13: '#EDA6FF'
  color14: '#B0E2FF'
  color15: '#FFFFFF'

i3wm/config:
  font: IBM Plex Sans
  fontsize: 13
  rofifont: IBM Plex Sans
  rofifontsize: 25
  mod: 'mod4'
  comment: ''
  raisevol: '\$mod+equal'
  lowervol: '\$mod+minus'
  mute: '\$mod+0'
  browser: ''
  email: ''
  bluetooth: '#'
  execst: '#'
  execalacritty: ''

dunstrc:
  font: IBM Plex Sans
  fontsize: 8

alacritty.yml:
  font: IBM Plex Mono
  fontsize: '12.0'
  decorations: 'full'

st/config.h:
  font: IBM Plex Mono
  size: 15
  font2: Jetbrains Mono
  size2: 15.5
  cwscale: 1
  chscale: 1
  bgcolor: '#1A1B1A'
  cscolor: '#5E81AC'
  rcscolor: '#D8DEE9'
  color0: '#3B4252'
  color1: '#BF616A'
  color2: '#A3BE8C'
  color3: '#EBCB8B'
  color4: '#81A1C1'
  color5: '#B48EAD'
  color6: '#88C0D0'
  color7: '#DADADA'
  color8: '#4C566A'
  color9: '#BF616A'
  color10: '#A3BE8C'
  color11: '#EBCB8B'
  color12: '#81A1C1'
  color13: '#B48EAD'
  color14: '#8FBCBB'
  color15: '#ECEFF4'

polybar/config.ini:
  font: IBM Plex Sans
  fontsize: 10
