#!/usr/bin/env bash
# Icon source from nerd-fonts:
#   https://github.com/ryanoasis/nerd-fonts/tree/master/bin/scripts/lib
test -n "$__icons_loaded" && return || __icons_loaded=1

# Defaults
i='' i_default=$i
i='' i_folder=$i

# Archives or compressed
i='' i_tar=$i
i='' i_tgz=$i
i='' i_arj=$i
i='' i_taz=$i
i='' i_lzh=$i
i='' i_lzma=$i
i='' i_tlz=$i
i='' i_txz=$i
i='' i_zip=$i
i='' i_z=$i
i='' i_Z=$i
i='' i_dz=$i
i='' i_gz=$i
i='' i_lz=$i
i='' i_xz=$i
i='' i_bz2=$i
i='' i_bz=$i
i='' i_tbz=$i
i='' i_tbz2=$i
i='' i_tz=$i
i='' i_deb=$i
i='' i_rpm=$i
i='' i_jar=$i
i='' i_rar=$i
i='' i_ace=$i
i='' i_zoo=$i
i='' i_cpio=$i
i='' i_7z=$i
i='' i_rz=$i
i='' i_apk=$i
i='' i_gem=$i

# Image
i='' i_jpg=$i
i='' i_jpeg=$i
i='' i_png=$i
i='' i_tif=$i
i='' i_tiff=$i
i='' i_gif=$i
i='' i_bmp=$i
i='' i_pbm=$i
i='' i_pgm=$i
i='' i_ppm=$i
i='' i_tga=$i
i='' i_xbm=$i
i='' i_xpm=$i
i='' i_svg=$i
i='' i_svgz=$i
i='' i_mng=$i
i='' i_pcx=$i
i='' i_dl=$i
i='' i_xcf=$i
i='' i_xwd=$i
i='' i_yuv=$i
i='' i_cgm=$i
i='' i_emf=$i
i='' i_eps=$i
i='' i_cr2=$i
i='' i_dng=$i
i='' i_ico=$i
i='' i_gpl=$i

# Video
i='' i_mov=$i
i='' i_mpg=$i
i='' i_mpeg=$i
i='' i_m2v=$i
i='' i_mkv=$i
i='' i_ogm=$i
i='' i_mp4=$i
i='' i_m4v=$i
i='' i_mp4v=$i
i='' i_vob=$i
i='' i_qt=$i
i='' i_nuv=$i
i='' i_wmv=$i
i='' i_asf=$i
i='' i_rm=$i
i='' i_rmvb=$i
i='' i_flc=$i
i='' i_avi=$i
i='' i_fli=$i
i='' i_flv=$i
i='' i_gl=$i
i='' i_m2ts=$i
i='' i_divx=$i
i='' i_webm=$i

# Audio
i='' i_aac=$i
i='' i_au=$i
i='' i_flac=$i
i='' i_mid=$i
i='' i_midi=$i
i='' i_mka=$i
i='' i_mp3=$i
i='' i_mpc=$i
i='' i_ogg=$i
i='' i_ra=$i
i='' i_wav=$i
i='' i_m4a=$i
i='' i_opus=$i

# Documents
i='' i_pdf=$i
i='' i_html=$i
i='' i_doc=$i
i='' i_docx=$i
i='' i_ppt=$i
i='' i_pptx=$i
i='' i_xls=$i
i='' i_xlsx=$i
i='' i_xlm=$i
i='' i_odt=$i
i='' i_odp=$i
i='' i_epub=$i
i='' i_mobi=$i
i='' i_azw3=$i
i='' i_xml=$i

# Source code files
i='' i_pl=$i
i='' i_py=$i
i='' i_sql=$i
i='' i_js=$i
i='' i_bash=$i
i='' i_sh=$i
i='' i_rb=$i
i='' i_c=$i
i='' i_lua=$i
i='' i_hs=$i
i='' i_vim=$i
i='' i_css=$i
i='' i_go=$i
i='' i_ts=$i
i='' i_conf=$i
i='' i_config=$i
i='' i_ini=$i
i='' i_rc=$i
i='' i_xmp=$i

# Plain text
i='' i_txt=$i
i='' i_srt=$i
i='' i_csv=$i
i='' i_list=$i
i='' i_md=$i
i='' i_markdown=$i
i='' i_yml=$i
i='' i_yaml=$i
i='' i_json=$i

# Others
i='' i_log=$i
i='' i_bak=$i
i='' i_part=$i
i='' i_swp=$i
i='' i_tmp=$i
i='' i_temp=$i
i='' i_pyc=$i
i='' i_cache=$i
i='' i_class=$i
i='' i_key=$i
i='' i_keystore=$i

unset i
